### ISSUE TITLE
Generación de Librerias incompleto . . .

### ISSUE THREAD

**Issue by gvaronas** [marcosgambeta/Qt5xHb#1]
Hola:
Env.
HB32
Win8Pro
QT551

Cuando intento generar las LIBS, solo me genera estas:
libhbqaxcontainer5.a
libhbqaxserver5.a
libhbqtbluetooth5.a
libhbqtcore5.a
libhbqtdeclarative5.a
libhbqtdesigner5.a
libhbqtgui5.a
libhbqthelp5.a
libhbqtmultimedia5.a
libhbqtmultimediawidgets5.a
libhbqtnetwork5.a
libhbqtopengl5.a

Tampoco ma da ningun error ni dice que me faltan generar LIB.

Luego cuando intento compilar los TEST, me dice que falta varias LIBS:
. . .
#: cannot find -lhbqtpositioning5
#: cannot find -lhbqtprintsupport5
#: cannot find -lhbqtqml5
#: cannot find -lhbqtquick5
#: cannot find -lhbqtquickwidgets5
#: cannot find -lhbqtscript5
#: cannot find -lhbqtscripttools5
#: cannot find -lhbqtsensors5
#: cannot find -lhbqtserialport5
#: cannot find -lhbqtsql5
#: cannot find -lhbqtsvg5
#: cannot find -lhbqtuitools5
#: cannot find -lhbqtwebsockets5
#: cannot find -lhbqtwebkit5
#: cannot find -lhbqtwebkitwidgets5
#: cannot find -lhbqtwidgets5
#: cannot find -lhbqtwinextras5
#: cannot find -lhbqtxml5
#: cannot find -lhbqtxmlpatterns5
#: cannot find -lQt5AxBase
#: cannot find -lQt5AxContainer
#: cannot find -lQt5Bluetooth
#: cannot find -lQt5CLucene
#: cannot find -lQt5Concurrent
#: cannot find -lQt5Core
#: cannot find -lQt5Declarative
#: cannot find -lQt5Designer
#: cannot find -lQt5DesignerComponents
#: cannot find -lQt5Gui
#: cannot find -lQt5Help
#: cannot find -lQt5Multimedia
#: cannot find -lQt5MultimediaQuick_p
#: cannot find -lQt5MultimediaWidgets
#: cannot find -lQt5Network
#: cannot find -lQt5Nfc
#: cannot find -lQt5OpenGL
#: cannot find -lQt5OpenGLExtensions
#: cannot find -lQt5PlatformSupport
#: cannot find -lQt5Positioning
#: cannot find -lQt5PrintSupport
#: cannot find -lQt5Qml
#: cannot find -lQt5QmlDevTools
#: cannot find -lQt5Quick
#: cannot find -lQt5QuickParticles
#: cannot find -lQt5QuickTest
#: cannot find -lQt5QuickWidgets
#: cannot find -lQt5Script
#: cannot find -lQt5ScriptTools
#: cannot find -lQt5Sensors
#: cannot find -lQt5SerialPort
#: cannot find -lQt5Sql
#: cannot find -lQt5Svg
#: cannot find -lQt5Test
#: cannot find -lQt5UiTools
#: cannot find -lQt5WebSockets
#: cannot find -lQt5WebKit
#: cannot find -lQt5WebKitWidgets
#: cannot find -lQt5Widgets
#: cannot find -lQt5WinExtras
#: cannot find -lQt5Xml
#: cannot find -lQt5XmlPatterns
. . .

y no se generan los EXE.

Espero me puedan ayudar para poder generar los EXE

Salu2,
GVS

**Comment by marcosgambeta** [comment]
The motive of the error is a bug in the Qt 5.5.1:

**source/QtPositioning/QGeoLocation.prg:57:24: fatal error: QGeoLocation: No such file or directory
 #include <QGeoLocation>
                        ^
compilation terminated.
mingw32-make: *** [obj/qt551/dynamic/mingw/32/windows/harbour/320dev/QGeoLocation.o] Error 1**

Update the code of the Qt5xHb project and see the misc folder (QGeoLocation.txt)

**Comment by gvaronas** [comment]
Hola Marcos:
Gracias por su respuesta.
He avanzado un poco mas, ahora se han generado 31 libs, pero esas son todas, por que resulta que al querer compilar el ejemplo mainwindow.prg, obtengo esto:
C:\Users\gvaronas\Documents\GitHub\Qt5xHb\tests>HBMK2 mainwindow ..\qt5xhb.hbc
Harbour 3.2.0dev (r1602181602)
Copyright (c) 1999-2016, http://harbour-project.org/
Compiling 'mainwindow.prg'...
Lines 13899, Functions/Procedures 10
Generating C source output to 'C:\Users\gvaronas\AppData\Local\Temp\hbmk_mjyt97.dir\mainwindow.c'... Done.
C:/Qt/Qt5.5.1/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe
: cannot find -lhbqaxcontainer5
C:/Qt/Qt5.5.1/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe
: cannot find -lhbqtbluetooth5
C:/Qt/Qt5.5.1/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe
: cannot find -lhbqtcore5
C:/Qt/Qt5.5.1/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe
: cannot find -lhbqtdeclarative5
C:/Qt/Qt5.5.1/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe
: cannot find -lhbqtdesigner5
C:/Qt/Qt5.5.1/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe
: cannot find -lhbqtgui5
C:/Qt/Qt5.5.1/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe
: cannot find -lhbqthelp5
C:/Qt/Qt5.5.1/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe
: cannot find -lhbqtmultimedia5
C:/Qt/Qt5.5.1/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe
: cannot find -lhbqtmultimediawidgets5
C:/Qt/Qt5.5.1/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe
: cannot find -lhbqtnetwork5
C:/Qt/Qt5.5.1/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe
: cannot find -lhbqtopengl5
collect2.exe: error: ld returned 1 exit status
hbmk2: Error: Ejecutando enlazador. 1
g++.exe C:/Users/gvaronas/AppData/Local/Temp/hbmk_mjyt97.dir/mainwindow.o C:/Users/gvaronas/AppData/Local/Tem
p/hbmk_mjyt97.dir/hbmk_mzyia8.o    -mwindows -Wl,--start-group -lhbqaxcontainer5 -lhbqtbluetooth5 -lhbqtcore5
 -lhbqtdeclarative5 -lhbqtdesigner5 -lhbqtgui5 -lhbqthelp5 -lhbqtmultimedia5 -lhbqtmultimediawidgets5 -lhbqtn
etwork5 -lhbqtopengl5 -lQt5AxBase -lQt5AxContainer -lQt5Bluetooth -lQt5CLucene -lQt5Concurrent -lQt5Core -lQt
5Declarative -lQt5Designer -lQt5DesignerComponents -lQt5Gui -lQt5Help -lQt5Multimedia -lQt5MultimediaQuick_p
-lQt5MultimediaWidgets -lQt5Network -lQt5Nfc -lQt5OpenGL -lQt5OpenGLExtensions -lQt5PlatformSupport -lQt5Posi
tioning -lQt5PrintSupport -lQt5Qml -lQt5QmlDevTools -lQt5Quick -lQt5QuickParticles -lQt5QuickTest -lQt5QuickW
idgets -lQt5Script -lQt5ScriptTools -lQt5Sensors -lQt5SerialPort -lQt5Sql -lQt5Svg -lQt5Test -lQt5UiTools -lQ
t5WebSockets -lQt5WebKit -lQt5WebKitWidgets -lQt5Widgets -lQt5WinExtras -lQt5Xml -lQt5XmlPatterns -lhbextern
-lhbdebug -lhbvm -lhbrtl -lhblang -lhbcpage -lgtcgi -lgtpca -lgtstd -lgtwin -lgtwvt -lgtgui -lhbrdd -lhbuddal
l -lhbusrrdd -lrddntx -lrddcdx -lrddnsx -lrddfpt -lhbrdd -lhbhsx -lhbsix -lhbmacro -lhbcplr -lhbpp -lhbcommon
 -lhbmainwin -lkernel32 -luser32 -lgdi32 -ladvapi32 -lws2_32 -liphlpapi -lwinspool -lcomctl32 -lcomdlg32 -lsh
ell32 -luuid -lole32 -loleaut32 -lmpr -lwinmm -lmapi32 -limm32 -lmsimg32 -lwininet -lhbpcre -lhbzlib   -Wl,--
end-group -omainwindow.exe  -LC:/Hb32/lib/win/mingw -LC:/Qt/Qt5.5.1/5.5/mingw492_32/lib

C:\Users\gvaronas\Documents\GitHub\Qt5xHb\tests>

Otra vez, no encuentra libs, al parecer pertenecen a Qt5xhb, ahora son menos.

Cuando vuelvo a darle para generar las Libs, me sale esto:
C:\Users\gvaronas\Documents\GitHub\Qt5xHb>mingw32-make -f makefile_mingw
mingw32-make: Nothing to be done for `all'.
C:\Users\gvaronas\Documents\GitHub\Qt5xHb>

Entonces supongo que ya no hay mas libs que crear.

¿Qué puede estar pasando?

Gracias por su tiempo.

Saludos
GVS

**Comment by marcosgambeta** [comment]
The total of libraries is correct: 31 files.

Check your prompt.bat. Something is wrong. See example below.

**Qt Framework path**
set QTDIR=C:\Qt\Qt5.5.1\5.5\mingw492_32
**Harbour path (compiled with MinGW 4.9.2)** 
set HBDIR=C:\Harbour
**MinGW 4.9.2 path**
set CPPDIR=C:\Qt\Qt5.5.1\Tools\mingw492_32
**Qt5xHb (include folder)**
set QT5XHB_INC_DIR=include
**Qt5xHb (lib folder)**
set QT5XHB_LIB_DIR=lib\qt551\dynamic\mingw\32\windows\harbour\320dev

**Comment by gvaronas** [comment]
Hola Marcos:
Al parecer el problema está en el uso de las versiones del compilador MinGW.

Tengo el HB32 Nightly con los siguientes datos del Build:

C:\Users\gvaronas\Documents\GitHub\Qt5xHb>harbour -build
Harbour 3.2.0dev (r1602181602)
Copyright (c) 1999-2016, http://harbour-project.org/
Harbour Build Info
Version: Harbour 3.2.0dev (r1602181602)
**Compiler: MinGW GNU C 5.3 (32-bit)**
Platform: Windows 8.1 6.3
PCode version: 0.3
ChangeLog last entry: 2016-02-18 17:02 UTC+0100 Przemyslaw Czerpak (druzus/at/poczta.onet.pl)
ChangeLog ID: 4e4f7e86646462b2e06ed2743103f53d19501977
Built on: Feb 23 2016 08:46:51
Build options: (Clipper 5.3b) (Clipper 5.x undoc)
---------------------------
C:\Users\gvaronas\Documents\GitHub\Qt5xHb>

y ahora no se como proceder para obtener un harbour compilado con  con MinGW 4.9.2.

¿Necesariamente tengo que tener el MinGW 4.9.2?
¿Puedo hacer que el proceso de generación de las LIBs de Qt5xHb sea con el MinGW 5.3 (Que es el que tengo en el HB32 Nightly)?

Gracias de antemano.

Salu2,
GVS

**Comment by marcosgambeta** [comment]
The best option is Qt + Harbour + Qt5xHb compiled with the same compiler.

But I'm doing some tests with the Harbour-nightly. I will share the results ASAP.

**Comment by gvaronas** [comment]
Ok. Marcos.
Quedo a la espera de los resultados.
Muchas Gracias.
Salu2,
GVS

**Comment by marcosgambeta** [comment]
Sorry, the binaries generated are unstable.

Please, try with the Harbour below:

http://www.mediafire.com/file/82yql0w5t6a388u/harbour320dev-qt551-mingw492-32bit-20170225-0002.7z

Compile Qt5xHb with the Harbour above and MinGW 4.9.2 (installed with Qt Framework 5.5.1).
